### ISSUE TITLE
travis.yml needs updating

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/mclass-sky#100]
The KNFST work might be not building, and is currently hidden by the broken travis file.

**Comment by alasdairtran** [comment]
Woohoo! 100 issues and pull requests :-P

Travis is fixed. Just need to include Cython dependency (b6ab49f88385e61fb6e16cef15986e975a9a0221) and remove a few old modules (d82ae724c6120eec0c19b0f386ad5e3183ac7c2d, f2c94c36558da6fefb8ff7460bad9c6e76d839db) and test cases (7fcd2626d89f16dca7dc50720a8e281215bff006).
