### ISSUE TITLE
Save results of experiments for PeerJ paper

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/mclass-sky#113]
Instead of just plotting the results, it would be useful to save all the data that is needed to plot the results, and then have all the plotting happen in one script. Of course, keep the original plotting in the notebooks for sanity checking in future.

The reason is that we may need to update the plots as we go for publication, and it would be silly to need to re-run a long experiment just to generate a plot.

**Comment by alasdairtran** [comment]
Yep sure, the data currently sit in my drive. The raw results are pretty big though (80 MB of uncompressed npy files). Would you like me to put them somewhere so that you and Chris can access them?

**Comment by chengsoonong** [comment]
That would be great. We might have to think about how to publish this, but we might be able to get PeerJ to take it as part of our supplement.

**Comment by chengsoonong** [comment]
Could you send Chris and I an email with a link to the data? I can try to figure out a cloudstor link if you send me an email address for you. Cloudstor would be a good place for you to upload data.

**Comment by chengsoonong** [comment]
Data stored using git lfs at:
https://gitlab.com/chengsoon.ong/mclass-sky-data
