### ISSUE TITLE
Louche and Ralaivola paper

### ISSUE THREAD

**Issue by davidjwu** [chengsoonong/mclass-sky#121]
Make notes on the Louche and Ralaivola paper ([pdf](http://arxiv.org/pdf/1508.02986v1.pdf)) and duplicate their experiments on a subset of the SDSS data set.

**Comment by davidjwu** [comment]
@chengsoonong The paper compares the performance of two active learning algorithms `Active-SVM` and `Active-BPM` with the difference being that the former is based on the Chebyshev center and the latter is based on the center of gravity. 

It seems `Active-SVM` was implemented using the package LIBSVM ([site](https://www.csie.ntu.edu.tw/~cjlin/libsvm/)), which has a Python interface. So I may attempt to replicate the results in the paper attained using LIBSVM. Alternatively, it appears computing the Chebyshev center reduces to solving a linear program, so attempting to do this directly using NumPy, SciPy or perhaps CVXOPT ([site](http://cvxopt.org/)) may be more straightforward.

Unfortunately, `Active-BPM` seems to have been implemented in MATLAB, which is problematic. I've been unable to find a Python package that I can use to computes the center of gravity. From what I can gather, computing the center of gravity is not straightforward at all.

**Comment by chengsoonong** [comment]
You do not need to compare with ```Active-BPM```.

I suggest comparing three algorithms in your work:
1. Algorithm 4 in the paper, with a uniform random point as **center(C^t)** (issue #123)
2. ACCPM with Algorithm 4 in the paper (issue #122)
3. (optional) Chebyshev center using [cvxpy](https://github.com/cvxgrp/cvxpy/blob/master/examples/chebyshev.py) (raise issue if you get here).

I suggest solving them in the suggested order above. Please confirm that you are happy with this plan @davidjwu, and we can close this issue.

**Comment by davidjwu** [comment]
@chengsoonong Yes, this plan seems reasonable.
