### ISSUE TITLE
ACCPM for active learning

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/mclass-sky#122]
Algorithm 4 in Louche and Ralaivola, From Cutting Planes Algorithms to Compression Schemes and Active Learning.

Related to issue #121

**Comment by chengsoonong** [comment]
It seems that this could also be closed @davidjwu ? If you already have a test toy example, we can close this. Please point to the toy example in your commit.

**Comment by davidjwu** [comment]
This was implemented in `active.py` and tested in both `experiment_active_iris.ipynb` and `experiment_active_diabetes.ipynb` so this issue can be closed.
