### ISSUE TITLE
README for David's ASC

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/mclass-sky#129]
Describe what the files and directories in the subtree projects/david contain.

**Comment by davidjwu** [comment]
@chengsoonong I saw this after I made a pull request submitting my report. If you like, you can reject the current pull request and I'll write this up, re-structure some folders and then make another.

**Comment by chengsoonong** [comment]
Please send me another pull request specifically closing this issue.

**Comment by chengsoonong** [comment]
Closed by #131
