### ISSUE TITLE
Implement tutorial regression

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/mclass-sky#132]
From GPy:
http://nbviewer.jupyter.org/github/SheffieldML/notebook/blob/master/GPy/basic_gp.ipynb
http://nbviewer.jupyter.org/github/SheffieldML/notebook/blob/master/GPy/basic_kernels.ipynb

**Comment by jakubnabaglo** [comment]
I’ve implemented Gaussian regression on the photometric redshift data. I have got some results, but I’m not sure how good they are. The R^2 value is 0.8827485892658886 on 1000 training samples and 1000 testing samples. Note that this does not take into account the uncertainties in the input data and in the labels.

**Comment by jakubnabaglo** [comment]
Gausssian processes seem to be learning well. The R^2 value is 0.8827485892658886 (on 1000 training samples and 1000 testing samples), whereas the R^2 value of the constant predictor is 0.08111539840227144 on the same samples.

Please accept pull request #136.

**Comment by chengsoonong** [comment]
Implemented in ce9ac96
