### ISSUE TITLE
Feature map kernel approximation

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/mclass-sky#140]
http://scikit-learn.org/stable/auto_examples/plot_kernel_approximation.html#sphx-glr-auto-examples-plot-kernel-approximation-py

Related to #133

**Comment by jakubnabaglo** [comment]
Done in 4f6b9bd. The new R^2 value is 0.842, compared to the previous value of 0.564 for SGD regression, and 0.911 for GP regression. I think I need to perform some cross validation.
