### ISSUE TITLE
GPflow Gaussian process regression

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/mclass-sky#144]
The belief is that tensorflow will speed things up compared to sklearn.
http://gpflow.readthedocs.io/en/latest/notebooks/regression.html

Sparse GPs (with inducing variables) will be faster than the standard GP.
http://gpflow.readthedocs.io/en/latest/model_options.html#sparse-gp-regression

**Comment by jakubnabaglo** [comment]
Solved in 4f6b9bd. It doesn’t appear significantly faster than Sklearn GP regression, but then again I am not running it on a GPU.

**Comment by chengsoonong** [comment]
Resolved in 704ffdc
