### ISSUE TITLE
Read GP-UCB

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/mclass-sky#146]
Write 3 pages to describe the results of GP-UCB:
https://arxiv.org/abs/0912.3995
http://ieeexplore.ieee.org/document/6138914/

**Comment by nbgl** [comment]
I’ve read about this and am using a recommender inspired by GP-UCB in the project. I don’t think it’s worth writing 3 pages at this stage, but I will mention it in my thesis.
