### ISSUE TITLE
Write: Kernelised linear regression

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/mclass-sky#153]
(to add to the gp.tex)

Consider linear regression with a basis function
y = w^\top \phi(x) + b
and recall the kernel trick:
k(x_i, x_j) = \dotprod{\phi(x_i)}{\phi(x_j)}

Derive the resulting predictor for a test point, and compare with the GP regressor.

**Comment by jakubnabaglo** [comment]
Make a note about heteroscedastic data.

**Comment by jakubnabaglo** [comment]
Aim is to prove equivalence of predictions with GP.

**Comment by nbgl** [comment]
Completed in 3afeb3b.
