### ISSUE TITLE
Plot learning curve of SGD and GP

### ISSUE THREAD

**Issue by nbgl** [chengsoonong/mclass-sky#165]
R^2 vs training point #.

**Comment by jakubnabaglo** [comment]
Progress made in ba42d23 (#169).

**Comment by jakubnabaglo** [comment]
Do passive learning curves second.

**Comment by nbgl** [comment]
I have obtained the following curve for passive learning. I am working on unifying SGD and GP and producing a better one.

From this, we can see that GP works very well on small training sets. Perhaps there is no need for SGD regression?

![curve](https://user-images.githubusercontent.com/12507513/27132286-a4925ccc-5151-11e7-909a-63c73aada07c.png)

**Comment by nbgl** [comment]
At long last, I produced correct curve! I take back what I said about not needing SGD regression: you can clearly see that the accuracy of SGD regression keeps increasing beyond 1.5K training points, which is where we stop being able to train GP regression.

![curve2](https://user-images.githubusercontent.com/12507513/27206147-d05e002c-5278-11e7-9dac-2ee4f0498a56.png)

**Comment by nbgl** [comment]
Completed for passive learning in 529ff9b.
