### ISSUE TITLE
Unify SGD and GP kernels

### ISSUE THREAD

**Issue by nbgl** [chengsoonong/mclass-sky#172]

**Comment by jakubnabaglo** [comment]
Solved in fa71e43. The R^2 for GP has decreased to 0.66 due to this, but I expect it can be improved by setting the hyperparameters.

**Comment by jakubnabaglo** [comment]
Find why results do not match.

**Comment by jakubnabaglo** [comment]
Do this first.

**Comment by nbgl** [comment]
Completed in 1b9baf1.
