### ISSUE TITLE
Fix writeup on kernelised linear regression

### ISSUE THREAD

**Issue by nbgl** [chengsoonong/mclass-sky#179]
- Use Moore-Penrose pseudoinverse for niceness.
- Add regularisation

**Comment by nbgl** [comment]
Completed in fdb1e83.

**Comment by chengsoonong** [comment]
Found a bug in your derivation.

f = phi(x)^\top w
and in your least squares error you say
f = Kw

The second is not correct. To go from the first to the second, you need to know that
K = \phi^\top \phi
The kernel trick:
k(x_i, x_j) = < \phi(x_i) , \phi(x_j) >

**Comment by nbgl** [comment]
Finished in 032cca0.
