### ISSUE TITLE
Prove empirical kernel map

### ISSUE THREAD

**Issue by nbgl** [chengsoonong/mclass-sky#183]
I’d like to convince myself of how it works

**Comment by chengsoonong** [comment]
There are two slides in the middle of this pack from Bernhard that should help.
http://mlg.eng.cam.ac.uk/mlss09/mlss_slides/Schoelkopf_1.pdf

**Comment by chengsoonong** [comment]
To learn about reproducing kernel Hilbert spaces, read Section 1.1.1 of
http://www.ong-home.my/papers/ong05thesis-accepted.pdf

**Comment by nbgl** [comment]
I switched to using a different kernel approximation in 20771f3. This is no longer directly relevant for now.

**Comment by nbgl** [comment]
This can be closed. I will include a proof in my thesis.
