### ISSUE TITLE
Use colours as features

### ISSUE THREAD

**Issue by nbgl** [chengsoonong/mclass-sky#193]
We have magnitudes in bands u, g, r, i, and z. Chris suggested using the differences in the magnitudes (colours) as features.

Replace:
- g with g - u,
- r with r - g,
- i with i - r, and
- z with z - i.

Test for improvement.

**Comment by nbgl** [comment]
It turns out to be much better. And active learning actually works now…

(The below is on 1000 components of kernel approximation.)
![diffs](https://user-images.githubusercontent.com/12507513/28808648-185d5faa-76c1-11e7-855d-37854da565c2.png)

Note:
1. Active learning does better than passive learning.
2. Accuracy of passive learning is still growing.

In fact, plotting passive learning to 50 000 points, we note that the accuracy is *still* growing.
![50kpassive](https://user-images.githubusercontent.com/12507513/28808679-58f3e3fe-76c1-11e7-854e-06c433b6bebe.png)

This tells us that this problem requires a lot of data.

Plotting active vs passive learning to 15k points, we see that the problem responds *very* well to active learning.

![15kactivevspassive](https://user-images.githubusercontent.com/12507513/28808702-81e3075e-76c1-11e7-9af1-0f23d1836058.png)

**Comment by chengsoonong** [comment]
1. Look at Section 2.3 and 4.1 of @alasdairtran honours thesis for colour indices. Please follow the convention.
2. Reconcile the contradiction that you are getting better empirical results here, while you have a theorem that says that differences should not add any information to a linear classifier (perhaps as a new issue).

**Comment by nbgl** [comment]
There is no contradiction. The proof states that the theorem does not apply to models where the data is transformed by a non-linear function.

**Comment by chengsoonong** [comment]
How is the transformation to colour indices a non-linear transformation?

**Comment by nbgl** [comment]
That particular transformation is linear. However, afterwards, we apply a non-linear transform (ϕ) to approximate the RBF kernel: it is not true that ϕ(g - u) = ϕ(g) - ϕ(u).

**Comment by nbgl** [comment]
Using the canonical colours produces the following learning curve:

![canonicalcolours](https://user-images.githubusercontent.com/12507513/28815987-889d8dec-76e6-11e7-82ce-b601aadc3e1c.png)

It does not appear to make a significant difference.

**Comment by chengsoonong** [comment]
That's excellent @nbgl ! The astronomers would be familiar with a particular choice of colour indices, and in fact would also be interested in a particular choice of x and y axis for plotting. It is generally good to keep with convention to aid interpretation and ease of understanding.

**Comment by nbgl** [comment]
This can be closed now.
