### ISSUE TITLE
Active learning via uncertainty sampling

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/mclass-sky#22]
See survey:
From Theories to Queries: Active Learning in Practice
Burr Settles

**Comment by chengsoonong** [comment]
Perform experiments on SDSS data following the protocol in [active learning for logistic regression](http://link.springer.com/article/10.1007%2Fs10994-007-5019-5) by Schein and Ungar, 2007.

**Comment by alasdairtran** [comment]
So far, I've implemented the two uncertainty sampling heuristics (maximising Shannon entropy and minimising the margin) and the two query by bagging heuristics (minimising the average margin and maximising the average KL divergence), as described in Schein.

I have yet to look at the remaining two heuristics - the entropy and the variance minimisation.

**Comment by chengsoonong** [comment]
1. Predict on whole subset of 100000 data points. Learning curve up to 1000 examples.
2. Repeat 10 trials of 100000 (non-overlapping) data points.

Three ways of subsampling:
1. random sample
2. balanced sample (33.3% per class)
3. true proportion sample (based on our estimate of whole dataset)

**Comment by chengsoonong** [comment]
Please add your PDF of the slides of the midterm to the repo. Generally not good practice, but the PDF is key to closing this issue.
