### ISSUE TITLE
LIBLINEAR warm start

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/mclass-sky#23]
It would be good to get warm start for LIBLINEAR working in sklearn.

http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
https://manojbits.wordpress.com/2014/07/28/scikit-learn-logistic-regression-cv-2/
http://www.csie.ntu.edu.tw/~cjlin/papers/ws/

**Comment by chengsoonong** [comment]
Available in sklearn 0.17.
http://scikit-learn.org/stable/whats_new.html#version-0-17

**Comment by alasdairtran** [comment]
Even though we can now set `warm_start=True`, at each iteration we still need to give the solver a sample that contains at least one example from each class. So it's probably still not applicable to this project where we only add one point to the training set at a time.
