### ISSUE TITLE
Use colour index as feature

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/mclass-sky#26]
Consider difference between Mag as features:

* u-v 
* v-g
* g-r
* r-i

**Comment by alasdairtran** [comment]
In addition to the four colour indices, maybe include one magnitude measurement as well.

Another option to consider is to drop an entire group (either Petrosian or PSF) altogether.

**Comment by chengsoonong** [comment]
Some results in sdss_features.ipynb in the merged pull request #33.
