### ISSUE TITLE
See if the features in the SDSS dataset need to be normalised

### ISSUE THREAD

**Issue by alasdairtran** [chengsoonong/mclass-sky#3]
A good starting point is [didbits](https://github.com/chengsoonong/didbits)

**Comment by chengsoonong** [comment]
In particular:
http://nbviewer.ipython.org/github/chengsoonong/didbits/blob/master/Normalisation/normalise_vector.ipynb

**Comment by alasdairtran** [comment]
Normalisation doesn't seem to improve the performance of the SDSS dataset, but the functions have been implemented in `scripts/data_processing.py`. See abb81ae71b35b9585ec4bd894f86b2b35e1915dc
