### ISSUE TITLE
Double loop validation to choose parameters

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/mclass-sky#31]
To choose good regularisation and kernel parameters, it is best to use a double loop validation method.

https://github.com/chengsoonong/didbits/blob/master/CrossVal/expt_protocol.ipynb

**Comment by alasdairtran** [comment]
I've done the inner loop (i.e. gridsearch). The outer loop would probably take too long. See [notebooks/04_learning_curves.ipynb](http://nbviewer.ipython.org/github/alasdairtran/mclearn/blob/master/notebooks/04_learning_curves.ipynb) for updated results.
