### ISSUE TITLE
do not import *

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/mclass-sky#42]
In many of the notebooks, there is the statement:
from mclearn import *

This is generally considered bad practice. Lots of discussion on stackoverflow.

**Comment by alasdairtran** [comment]
Done in 7307ecb87fe0d154503fc10860c712c4638db085

**Comment by chengsoonong** [comment]
It seems that all the importing is now happening at the package level. I mean, __init__.py now contains import *

**Comment by alasdairtran** [comment]
This is fixed in 1d74fbf4f94580b9b19d9303903bfc54a0df8f29. Everything must now be imported explicitly.
