### ISSUE TITLE
update data to allow for reddening correction

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/mclass-sky#43]
The current data on the nicta filestore does not have extinction values.

**Comment by chengsoonong** [comment]
For reproducible research, we should have a script that downloads the data and does the cleaning mentioned in about_sdss.ipynb to create sdss_dr7_photometry.csv.gz

**Comment by chengsoonong** [comment]
A second script should be written to write a new file containing the colour indices which are reddenning corrected. Do not update the original raw data file.

**Comment by alasdairtran** [comment]
The SDSS server has a 1-minute time-out for automatic scripts, so unfortunately, if someone wants to get data on 2.8 million objects, they still have to manually create an account in [CasJobs](http://skyserver.sdss.org/casjobs/) and wait in a queue. I can give some instructions on how to do this in the notebook.

I don't think I have access to the NICTA filestore. Shall I wait for you to get back to give you the updated version of the dataset?

**Comment by chengsoonong** [comment]
I think it is fine to have to manually create an account. So, once the account is created, the user can cut and paste the SQL query?

I will upload the two new data files (the original data from SDSS and the preprocessed one) when I get back.

**Comment by alasdairtran** [comment]
I have uploaded the big datasets (except sdss_full.h5 which is 150GB) to my DropBox [here](https://www.dropbox.com/sh/koivdbxf2a3zivt/AABA7AJnR6DwipWIwtN2rCXCa?dl=0). You can transfer them to the NICTA filestore and update the README.

**Comment by chengsoonong** [comment]
In notebook 01_getting_sdss_dataset.ipynb, there is a link to a file:
http://filestore.nicta.com.au/mlrg-data/astro/sdss_dr7_photometry.csv.gz

Not sure whether this is still relevant. Or should this be sdss_dr7_photometry_source.csv.gz?

**Comment by chengsoonong** [comment]
README updated in commit 8be13fd996712e3037eeab4fb1c4d11fe72706ff
