### ISSUE TITLE
Use bandits to choose between active learning strategies

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/mclass-sky#53]
Consider the four active learning strategies from Schein and Ungar as four arms of a bandit problem. Some careful thought needs to be put into designing a good reward function.

It would be convenient if the rewards had structured that would allow kl-UCB or KL-UCB to be applied.

KULLBACK–LEIBLER UPPER CONFIDENCE BOUNDS FOR OPTIMAL SEQUENTIAL ALLOCATION
BY OLIVIER CAPPÉ, AURÉLIEN GARIVIER, ODALRIC-AMBRYM MAILLARD1, RÉMI MUNOS1 AND GILLES STOLTZ1

**Comment by chengsoonong** [comment]
Chapter 2 of
http://www.ii.uni.wroc.pl/~lukstafi/pmwiki/uploads/AGT/Prediction_Learning_and_Games.pdf
gives good background on learning with expert advice.

**Comment by alasdairtran** [comment]
See cefeef28988fd5504415ab4f6635503f560c5932 for some preliminary results.
