### ISSUE TITLE
Package on PyPI is missing DESCRIPTION.rst

### ISSUE THREAD

**Issue by yen223** [chengsoonong/mclass-sky#56]
`pip install mclearn` doesn't work out of the box because the package is missing DESCRIPTION.rst.

**Comment by alasdairtran** [comment]
Hey Wei Yen, what's your pypi username?

**Comment by yen223** [comment]
“weiyen"

**Comment by alasdairtran** [comment]
Awesome. I have added you as an owner of `mclearn`.

I use the following commands to do a test upload:

```
python setup.py register -r pypitest
python setup.py sdist upload -r pypitest
```

And to actually upload the package:

```
python setup.py register -r pypi
python setup.py sdist upload -r pypi
```

**Comment by chengsoonong** [comment]
Please add me too.
cong

**Comment by alasdairtran** [comment]
Added.

Also see ee99b5026176de818b613eadaf5b68c5e9ff5d7b for the new MANIFEST file. Package should now compile.
