### ISSUE TITLE
Look at inherently muliclass classifiers

### ISSUE THREAD

**Issue by alasdairtran** [chengsoonong/mclass-sky#6]
From the [docs](http://scikit-learn.org/stable/modules/multiclass.html), it looks like only 5 classifiers inherently support multiclass in sklearn: Naive Bayes, LDA, Decision Trees, Random Forests and Nearest Neighbours.

Support vector machine uses the one-vs-one strategy to do multiclass classification. Other linear models, including logistic regression, use one-vs-rest in sklearn.

**Comment by chengsoonong** [comment]
One other option is http://www.shogun-toolbox.org/, which has both one vs rest logistic regression and multiclass logistic regression.

**Comment by alasdairtran** [comment]
Shogun doesn't play well with Windows though :-(

**Comment by chengsoonong** [comment]
It is customary to refer to a commit hash when closing an issue.

On 2 Mar 2015 09:54, Alasdair Tran <notifications@github.com> wrote:

Closed #6<https://github.com/chengsoonong/mclass-sky/issues/6>.

**Comment by chengsoonong** [comment]
Ah yes, I forgot about that. Might have to put this on the back burner till after your confirmation.

On 2 Mar 2015 09:54, Alasdair Tran <notifications@github.com> wrote:

Shogun doesn't play well with Windows though :-(
