### ISSUE TITLE
Sanity check with UCI data

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/mclass-sky#61]
For testing purposes, it is good to have some easy UCI datasets to check that everything is working. The small datasets also mean that the computations should not take too long.

* [glass](http://mldata.org/repository/data/viewslug/glass/)
* [vehicle](http://mldata.org/repository/data/viewslug/vehicle/)
* [wine](http://mldata.org/repository/data/viewslug/wine/)

**Comment by alasdairtran** [comment]
`glass` has been added as a test dataset in 618a89d69b257b7676d160a47027724dc2ba84d6

**Comment by alasdairtran** [comment]
`wine` has been added, along with some unit tests. See 70f88448ce49daac4c34dc8fb574369e827a18c3
