### ISSUE TITLE
Contribution of thesis

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/mclass-sky#67]
Last section of introduction

**Comment by alasdairtran** [comment]
Added to introduction. See 89b4e768580e75e264c329b93688263f16335e28

**Comment by chengsoonong** [comment]
Do not downplay the contribution of applying the heuristics in Schein and Ungar to a novel domain. As far as we know, this application to photometry is new. Also, your contribution of identifying good features (e.g. polynomial kernel) and comparing different classifier is new.

**Comment by chengsoonong** [comment]
Is the performance measures from somewhere else? Seems new to me too.

**Comment by chengsoonong** [comment]
Identifying the best active learning heuristic for photometric classification is also new.

Furthermore, you applied a method developed on SDSS to data from the southern sky. This might be worth a chapter by itself. The reason is that the astronomers will not care about all the ML stuff, but will want to know whether it is worth learning about the ML stuff. You should convince them in a chapter about VST/ATLAS that they should read your other chapters.
