### ISSUE TITLE
zenodo

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/mclass-sky#99]
Minor things:
- Link from README seems broken.
- I think it would be nicer to collect the badges together at the top (if possible)
- Please add cong on zenodo so that I could potentially edit it in future.

**Comment by alasdairtran** [comment]
The link is working now. I think it takes a few days for the DOI to get activated.

I've added you as an author, but I'm not sure if there is a way to give you edit access. It looks like only the uploader can make changes :-/
